bundler_args: --without development
before_install:
  - gem update --system
  - gem update bundler
cache: bundler
language: ruby
rvm:
  - 2.5.0
  - 2.6.0
  - 2.7.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
sudo: false
